# Generated by Django 4.0.4 on 2022-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
